---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'Alix'

Product:
  extensions:
    - ProductExtension

Page:
  extensions:
    - FlexSliderExtension

ShoppingCart_Controller:
  direct_to_cart_page: true